//
// AntispamAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AntispamAPI {

    /**
     Add maildata to antispam engine
     
     - parameter addAntispamMaildataRequest: (body) Maildata payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func addAntispamMaildata(addAntispamMaildataRequest: AddAntispamMaildataRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await addAntispamMaildataWithRequestBuilder(addAntispamMaildataRequest: addAntispamMaildataRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add maildata to antispam engine
     - POST /antispam/maildata
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter addAntispamMaildataRequest: (body) Maildata payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func addAntispamMaildataWithRequestBuilder(addAntispamMaildataRequest: AddAntispamMaildataRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/antispam/maildata"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: addAntispamMaildataRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check maildata against existing antispam rules
     
     - parameter checkAntispamMaildataRulesRequest: (body) Maildata payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func checkAntispamMaildataRules(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await checkAntispamMaildataRulesWithRequestBuilder(checkAntispamMaildataRulesRequest: checkAntispamMaildataRulesRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check maildata against existing antispam rules
     - POST /antispam/maildata/check
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter checkAntispamMaildataRulesRequest: (body) Maildata payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func checkAntispamMaildataRulesWithRequestBuilder(checkAntispamMaildataRulesRequest: CheckAntispamMaildataRulesRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/antispam/maildata/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: checkAntispamMaildataRulesRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Create antispam email rule or increment existing rule hitcount
     
     - parameter createAntispamEmailRuleRequest: (body) Antispam email rule payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func createAntispamEmailRule(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await createAntispamEmailRuleWithRequestBuilder(createAntispamEmailRuleRequest: createAntispamEmailRuleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create antispam email rule or increment existing rule hitcount
     - POST /antispam/rules
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createAntispamEmailRuleRequest: (body) Antispam email rule payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func createAntispamEmailRuleWithRequestBuilder(createAntispamEmailRuleRequest: CreateAntispamEmailRuleRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/antispam/rules"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createAntispamEmailRuleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
