//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AuthAPI {

    /**
     Create anonymous auth token
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateAuthToken200Response
     */
    open class func createAuthToken(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateAuthToken200Response {
        return try await createAuthTokenWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create anonymous auth token
     - POST /auth/token
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateAuthToken200Response> 
     */
    open class func createAuthTokenWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateAuthToken200Response> {
        let localVariablePath = "/auth/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateAuthToken200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
