//
// CartAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CartAPI {

    /**
     Check and apply cart coupon
     
     - parameter checkCartCouponRequest: (body) Cart coupon check payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func checkCartCoupon(checkCartCouponRequest: CheckCartCouponRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await checkCartCouponWithRequestBuilder(checkCartCouponRequest: checkCartCouponRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check and apply cart coupon
     - POST /cart/coupons/check
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter checkCartCouponRequest: (body) Cart coupon check payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func checkCartCouponWithRequestBuilder(checkCartCouponRequest: CheckCartCouponRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/coupons/check"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: checkCartCouponRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Add item to cart
     
     - parameter createCartItemRequest: (body) Cart item add payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func createCartItem(createCartItemRequest: CreateCartItemRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await createCartItemWithRequestBuilder(createCartItemRequest: createCartItemRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add item to cart
     - POST /cart/items
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createCartItemRequest: (body) Cart item add payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func createCartItemWithRequestBuilder(createCartItemRequest: CreateCartItemRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/items"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCartItemRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Remove item from cart
     
     - parameter cartItemId: (path) Cart item ID 
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func deleteCartItem(cartItemId: Int, cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await deleteCartItemWithRequestBuilder(cartItemId: cartItemId, cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Remove item from cart
     - DELETE /cart/items/{cartItemId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cartItemId: (path) Cart item ID 
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func deleteCartItemWithRequestBuilder(cartItemId: Int, cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/cart/items/{cartItemId}"
        let cartItemIdPreEscape = "\(APIHelper.mapValueToPathItem(cartItemId))"
        let cartItemIdPostEscape = cartItemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{cartItemId}", with: cartItemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get cart billing address
     
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func getCartBillingAddress(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await getCartBillingAddressWithRequestBuilder(cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get cart billing address
     - GET /cart/billing-address
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func getCartBillingAddressWithRequestBuilder(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/billing-address"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get current cart coupon
     
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func getCartCoupon(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await getCartCouponWithRequestBuilder(cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get current cart coupon
     - GET /cart/coupons/current
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func getCartCouponWithRequestBuilder(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/coupons/current"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get cart total
     
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func getCartTotal(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await getCartTotalWithRequestBuilder(cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get cart total
     - GET /cart/total
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cname: (query) Customer name (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func getCartTotalWithRequestBuilder(cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/total"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List cart items
     
     - parameter cname: (query) Customer name (optional)
     - parameter lang: (query) Response language (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func listCartItems(cname: String? = nil, lang: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await listCartItemsWithRequestBuilder(cname: cname, lang: lang, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List cart items
     - GET /cart/items
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cname: (query) Customer name (optional)
     - parameter lang: (query) Response language (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func listCartItemsWithRequestBuilder(cname: String? = nil, lang: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/items"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "lang": (wrappedValue: lang?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Merge anonymous cart items into current customer cart
     
     - parameter mergeCartItemsRequest: (body) Anonymous cart merge payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MergeCartItems200Response
     */
    open class func mergeCartItems(mergeCartItemsRequest: MergeCartItemsRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> MergeCartItems200Response {
        return try await mergeCartItemsWithRequestBuilder(mergeCartItemsRequest: mergeCartItemsRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Merge anonymous cart items into current customer cart
     - POST /cart/items/merge
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter mergeCartItemsRequest: (body) Anonymous cart merge payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MergeCartItems200Response> 
     */
    open class func mergeCartItemsWithRequestBuilder(mergeCartItemsRequest: MergeCartItemsRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<MergeCartItems200Response> {
        let localVariablePath = "/cart/items/merge"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: mergeCartItemsRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MergeCartItems200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update cart item data
     
     - parameter cartItemId: (path) Cart item ID 
     - parameter updateCartItemRequest: (body) Cart item update payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func updateCartItem(cartItemId: Int, updateCartItemRequest: UpdateCartItemRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await updateCartItemWithRequestBuilder(cartItemId: cartItemId, updateCartItemRequest: updateCartItemRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update cart item data
     - PATCH /cart/items/{cartItemId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cartItemId: (path) Cart item ID 
     - parameter updateCartItemRequest: (body) Cart item update payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func updateCartItemWithRequestBuilder(cartItemId: Int, updateCartItemRequest: UpdateCartItemRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/cart/items/{cartItemId}"
        let cartItemIdPreEscape = "\(APIHelper.mapValueToPathItem(cartItemId))"
        let cartItemIdPostEscape = cartItemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{cartItemId}", with: cartItemIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCartItemRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update cart item count by product and domain
     
     - parameter updateCartItemCountRequest: (body) Cart item count update payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func updateCartItemCount(updateCartItemCountRequest: UpdateCartItemCountRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await updateCartItemCountWithRequestBuilder(updateCartItemCountRequest: updateCartItemCountRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update cart item count by product and domain
     - PATCH /cart/items/by-product/count
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter updateCartItemCountRequest: (body) Cart item count update payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func updateCartItemCountWithRequestBuilder(updateCartItemCountRequest: UpdateCartItemCountRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/cart/items/by-product/count"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCartItemCountRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
