//
// DNSAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DNSAPI {

    /**
     Create DNS record
     
     - parameter domain: (path) Domain name 
     - parameter createDnsRecordRequest: (body) DNS record payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func createDnsRecord(domain: String, createDnsRecordRequest: CreateDnsRecordRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await createDnsRecordWithRequestBuilder(domain: domain, createDnsRecordRequest: createDnsRecordRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create DNS record
     - POST /dns/{domain}/records
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter createDnsRecordRequest: (body) DNS record payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func createDnsRecordWithRequestBuilder(domain: String, createDnsRecordRequest: CreateDnsRecordRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/dns/{domain}/records"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createDnsRecordRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete DNS record
     
     - parameter domain: (path) Domain name 
     - parameter recordId: (path) Record ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func deleteDnsRecord(domain: String, recordId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await deleteDnsRecordWithRequestBuilder(domain: domain, recordId: recordId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete DNS record
     - DELETE /dns/{domain}/records/{recordId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter recordId: (path) Record ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func deleteDnsRecordWithRequestBuilder(domain: String, recordId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/dns/{domain}/records/{recordId}"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let recordIdPreEscape = "\(APIHelper.mapValueToPathItem(recordId))"
        let recordIdPostEscape = recordIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordId}", with: recordIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get DNS records by domain
     
     - parameter domain: (path) Domain name 
     - parameter type: (query) Filter records by type (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetDnsRecords200Response
     */
    open class func getDnsRecords(domain: String, type: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> GetDnsRecords200Response {
        return try await getDnsRecordsWithRequestBuilder(domain: domain, type: type, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get DNS records by domain
     - GET /dns/{domain}/records
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter type: (query) Filter records by type (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetDnsRecords200Response> 
     */
    open class func getDnsRecordsWithRequestBuilder(domain: String, type: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<GetDnsRecords200Response> {
        var localVariablePath = "/dns/{domain}/records"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "type": (wrappedValue: type?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetDnsRecords200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update DNS record
     
     - parameter domain: (path) Domain name 
     - parameter recordId: (path) Record ID 
     - parameter updateDnsRecordRequest: (body) Partial DNS record payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func updateDnsRecord(domain: String, recordId: Int, updateDnsRecordRequest: UpdateDnsRecordRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await updateDnsRecordWithRequestBuilder(domain: domain, recordId: recordId, updateDnsRecordRequest: updateDnsRecordRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update DNS record
     - PATCH /dns/{domain}/records/{recordId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter recordId: (path) Record ID 
     - parameter updateDnsRecordRequest: (body) Partial DNS record payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func updateDnsRecordWithRequestBuilder(domain: String, recordId: Int, updateDnsRecordRequest: UpdateDnsRecordRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/dns/{domain}/records/{recordId}"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let recordIdPreEscape = "\(APIHelper.mapValueToPathItem(recordId))"
        let recordIdPostEscape = recordIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordId}", with: recordIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateDnsRecordRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
