//
// DomainAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DomainAPI {

    /**
     Change domain nameservers
     
     - parameter domain: (path) Domain name 
     - parameter changeDomainNameserversRequest: (body) Nameserver payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func changeDomainNameservers(domain: String, changeDomainNameserversRequest: ChangeDomainNameserversRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await changeDomainNameserversWithRequestBuilder(domain: domain, changeDomainNameserversRequest: changeDomainNameserversRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Change domain nameservers
     - PATCH /domains/{domain}/nameservers
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter changeDomainNameserversRequest: (body) Nameserver payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func changeDomainNameserversWithRequestBuilder(domain: String, changeDomainNameserversRequest: ChangeDomainNameserversRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/domains/{domain}/nameservers"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: changeDomainNameserversRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Close external customer domain product
     
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func closeDomain(domain: String, cname: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await closeDomainWithRequestBuilder(domain: domain, cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Close external customer domain product
     - DELETE /domains/{domain}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func closeDomainWithRequestBuilder(domain: String, cname: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/domains/{domain}"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get domain information and availability
     
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name for product context (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func getDomainInfo(domain: String, cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await getDomainInfoWithRequestBuilder(domain: domain, cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get domain information and availability
     - GET /domains/{domain}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name for product context (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func getDomainInfoWithRequestBuilder(domain: String, cname: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/domains/{domain}"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List customer domains
     
     - parameter cname: (query) Customer name 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ListDomains200Response
     */
    open class func listDomains(cname: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ListDomains200Response {
        return try await listDomainsWithRequestBuilder(cname: cname, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List customer domains
     - GET /domains
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter cname: (query) Customer name 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ListDomains200Response> 
     */
    open class func listDomainsWithRequestBuilder(cname: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<ListDomains200Response> {
        let localVariablePath = "/domains"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListDomains200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Register domain
     
     - parameter domain: (path) Domain name 
     - parameter registerDomainRequest: (body) Domain registration payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func registerDomain(domain: String, registerDomainRequest: RegisterDomainRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await registerDomainWithRequestBuilder(domain: domain, registerDomainRequest: registerDomainRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Register domain
     - POST /domains/{domain}/register
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter registerDomainRequest: (body) Domain registration payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func registerDomainWithRequestBuilder(domain: String, registerDomainRequest: RegisterDomainRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/domains/{domain}/register"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerDomainRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Renew domain
     
     - parameter domain: (path) Domain name 
     - parameter renewDomainRequest: (body) Domain renewal payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func renewDomain(domain: String, renewDomainRequest: RenewDomainRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await renewDomainWithRequestBuilder(domain: domain, renewDomainRequest: renewDomainRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Renew domain
     - POST /domains/{domain}/renew
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter renewDomainRequest: (body) Domain renewal payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func renewDomainWithRequestBuilder(domain: String, renewDomainRequest: RenewDomainRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/domains/{domain}/renew"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: renewDomainRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Check domain WHOIS availability and prices
     
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name for price context (optional)
     - parameter currencyId: (query) Currency ID (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: WhoisDomain200Response
     */
    open class func whoisDomain(domain: String, cname: String? = nil, currencyId: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> WhoisDomain200Response {
        return try await whoisDomainWithRequestBuilder(domain: domain, cname: cname, currencyId: currencyId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Check domain WHOIS availability and prices
     - GET /domains/{domain}/whois
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter domain: (path) Domain name 
     - parameter cname: (query) Customer name for price context (optional)
     - parameter currencyId: (query) Currency ID (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<WhoisDomain200Response> 
     */
    open class func whoisDomainWithRequestBuilder(domain: String, cname: String? = nil, currencyId: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<WhoisDomain200Response> {
        var localVariablePath = "/domains/{domain}/whois"
        let domainPreEscape = "\(APIHelper.mapValueToPathItem(domain))"
        let domainPostEscape = domainPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{domain}", with: domainPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cname": (wrappedValue: cname?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "currency_id": (wrappedValue: currencyId?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WhoisDomain200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
