//
// LLMAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class LLMAPI {

    /**
     Classify a web form message as spam or ham using the local LLM
     
     - parameter spamDetectionRequest: (body) Spam detection payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpamDetection200Response
     */
    open class func spamDetection(spamDetectionRequest: SpamDetectionRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> SpamDetection200Response {
        return try await spamDetectionWithRequestBuilder(spamDetectionRequest: spamDetectionRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Classify a web form message as spam or ham using the local LLM
     - POST /llm/spam-detection
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter spamDetectionRequest: (body) Spam detection payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpamDetection200Response> 
     */
    open class func spamDetectionWithRequestBuilder(spamDetectionRequest: SpamDetectionRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<SpamDetection200Response> {
        let localVariablePath = "/llm/spam-detection"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: spamDetectionRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpamDetection200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
