//
// OAuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OAuthAPI {

    /**
     Create OAuth request
     
     - parameter createOauthRequestRequest: (body) OAuth create payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateOauthRequest200Response
     */
    open class func createOauthRequest(createOauthRequestRequest: CreateOauthRequestRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateOauthRequest200Response {
        return try await createOauthRequestWithRequestBuilder(createOauthRequestRequest: createOauthRequestRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create OAuth request
     - POST /oauth/requests
     - parameter createOauthRequestRequest: (body) OAuth create payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateOauthRequest200Response> 
     */
    open class func createOauthRequestWithRequestBuilder(createOauthRequestRequest: CreateOauthRequestRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateOauthRequest200Response> {
        let localVariablePath = "/oauth/requests"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createOauthRequestRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateOauthRequest200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Delete OAuth token
     
     - parameter token: (query) OAuth token 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeleteOauthToken200Response
     */
    open class func deleteOauthToken(token: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> DeleteOauthToken200Response {
        return try await deleteOauthTokenWithRequestBuilder(token: token, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete OAuth token
     - DELETE /oauth/tokens
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter token: (query) OAuth token 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeleteOauthToken200Response> 
     */
    open class func deleteOauthTokenWithRequestBuilder(token: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<DeleteOauthToken200Response> {
        let localVariablePath = "/oauth/tokens"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "token": (wrappedValue: token.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeleteOauthToken200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List available OAuth scopes
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetOauthScopes200Response
     */
    open class func getOauthScopes(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> GetOauthScopes200Response {
        return try await getOauthScopesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List available OAuth scopes
     - GET /oauth/scopes
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetOauthScopes200Response> 
     */
    open class func getOauthScopesWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<GetOauthScopes200Response> {
        let localVariablePath = "/oauth/scopes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOauthScopes200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Refresh OAuth token
     
     - parameter refreshOauthTokenRequest: (body) OAuth refresh payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VerifyOauthRequest200Response
     */
    open class func refreshOauthToken(refreshOauthTokenRequest: RefreshOauthTokenRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> VerifyOauthRequest200Response {
        return try await refreshOauthTokenWithRequestBuilder(refreshOauthTokenRequest: refreshOauthTokenRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Refresh OAuth token
     - POST /oauth/tokens/refresh
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter refreshOauthTokenRequest: (body) OAuth refresh payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VerifyOauthRequest200Response> 
     */
    open class func refreshOauthTokenWithRequestBuilder(refreshOauthTokenRequest: RefreshOauthTokenRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<VerifyOauthRequest200Response> {
        let localVariablePath = "/oauth/tokens/refresh"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshOauthTokenRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyOauthRequest200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Verify OAuth request
     
     - parameter verifyToken: (query) Verify token from OAuth create response 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VerifyOauthRequest200Response
     */
    open class func verifyOauthRequest(verifyToken: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> VerifyOauthRequest200Response {
        return try await verifyOauthRequestWithRequestBuilder(verifyToken: verifyToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Verify OAuth request
     - GET /oauth/requests/verify
     - parameter verifyToken: (query) Verify token from OAuth create response 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VerifyOauthRequest200Response> 
     */
    open class func verifyOauthRequestWithRequestBuilder(verifyToken: String, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<VerifyOauthRequest200Response> {
        let localVariablePath = "/oauth/requests/verify"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "verify_token": (wrappedValue: verifyToken.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VerifyOauthRequest200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
