//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     Returns greeting message
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Hello200Response
     */
    open class func hello(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Hello200Response {
        return try await helloWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Returns greeting message
     - GET /system/hello
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Hello200Response> 
     */
    open class func helloWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<Hello200Response> {
        let localVariablePath = "/system/hello"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Hello200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Returns revision number of system
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Revision200Response
     */
    open class func revision(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Revision200Response {
        return try await revisionWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Returns revision number of system
     - GET /system/revision
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Revision200Response> 
     */
    open class func revisionWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<Revision200Response> {
        let localVariablePath = "/system/revision"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Revision200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Returns current date and time of system
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Time200Response
     */
    open class func time(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Time200Response {
        return try await timeWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Returns current date and time of system
     - GET /system/time
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Time200Response> 
     */
    open class func timeWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<Time200Response> {
        let localVariablePath = "/system/time"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Time200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
