//
// VehicleAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class VehicleAPI {

    /**
     Create vehicle event without receipt image
     
     - parameter createVehicleEventRequest: (body) Vehicle event create payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func createVehicleEvent(createVehicleEventRequest: CreateVehicleEventRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await createVehicleEventWithRequestBuilder(createVehicleEventRequest: createVehicleEventRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create vehicle event without receipt image
     - POST /vehicle/events
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createVehicleEventRequest: (body) Vehicle event create payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func createVehicleEventWithRequestBuilder(createVehicleEventRequest: CreateVehicleEventRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createVehicleEventRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete vehicle event
     
     - parameter eventId: (path) Vehicle event ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func deleteVehicleEvent(eventId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await deleteVehicleEventWithRequestBuilder(eventId: eventId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete vehicle event
     - DELETE /vehicle/events/{eventId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path) Vehicle event ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func deleteVehicleEventWithRequestBuilder(eventId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/vehicle/events/{eventId}"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Finalize vehicle event draft
     
     - parameter eventId: (path) Vehicle event ID 
     - parameter finalizeVehicleEventRequest: (body) Vehicle event finalize payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func finalizeVehicleEvent(eventId: Int, finalizeVehicleEventRequest: FinalizeVehicleEventRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await finalizeVehicleEventWithRequestBuilder(eventId: eventId, finalizeVehicleEventRequest: finalizeVehicleEventRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Finalize vehicle event draft
     - POST /vehicle/events/{eventId}/finalize
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path) Vehicle event ID 
     - parameter finalizeVehicleEventRequest: (body) Vehicle event finalize payload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func finalizeVehicleEventWithRequestBuilder(eventId: Int, finalizeVehicleEventRequest: FinalizeVehicleEventRequest, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/vehicle/events/{eventId}/finalize"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: finalizeVehicleEventRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get vehicle event detail
     
     - parameter eventId: (path) Vehicle event ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func getVehicleEvent(eventId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await getVehicleEventWithRequestBuilder(eventId: eventId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get vehicle event detail
     - GET /vehicle/events/{eventId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path) Vehicle event ID 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func getVehicleEventWithRequestBuilder(eventId: Int, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/vehicle/events/{eventId}"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get event image or thumbnail
     
     - parameter eventId: (path) Vehicle event ID 
     - parameter size: (query) Image size variant: thumb, thumbnail or small for thumbnail response (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: URL
     */
    open class func getVehicleEventImage(eventId: Int, size: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> URL {
        return try await getVehicleEventImageWithRequestBuilder(eventId: eventId, size: size, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get event image or thumbnail
     - GET /vehicle/events/{eventId}/image
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path) Vehicle event ID 
     - parameter size: (query) Image size variant: thumb, thumbnail or small for thumbnail response (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<URL> 
     */
    open class func getVehicleEventImageWithRequestBuilder(eventId: Int, size: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<URL> {
        var localVariablePath = "/vehicle/events/{eventId}/image"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "size": (wrappedValue: size?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List currencies for vehicle events
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func listVehicleCurrencies(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await listVehicleCurrenciesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List currencies for vehicle events
     - GET /vehicle/currencies
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func listVehicleCurrenciesWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/currencies"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List vehicle events for the authenticated driver
     
     - parameter since: (query) Return events with event datetime greater than or equal to the provided local datetime (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func listVehicleEvents(since: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await listVehicleEventsWithRequestBuilder(since: since, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List vehicle events for the authenticated driver
     - GET /vehicle/events
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter since: (query) Return events with event datetime greater than or equal to the provided local datetime (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func listVehicleEventsWithRequestBuilder(since: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/events"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "since": (wrappedValue: since?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List vehicles available to the authenticated driver
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func listVehicleVehicles(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await listVehicleVehiclesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List vehicles available to the authenticated driver
     - GET /vehicle/vehicles
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func listVehicleVehiclesWithRequestBuilder(apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/vehicles"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Replace event image and rescan event data
     
     - parameter eventId: (path) Vehicle event ID 
     - parameter image: (form)  
     - parameter timezone: (form)  (optional)
     - parameter eventType: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func rescanVehicleEventImage(eventId: Int, image: URL, timezone: String? = nil, eventType: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await rescanVehicleEventImageWithRequestBuilder(eventId: eventId, image: image, timezone: timezone, eventType: eventType, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Replace event image and rescan event data
     - POST /vehicle/events/{eventId}/image
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter eventId: (path) Vehicle event ID 
     - parameter image: (form)  
     - parameter timezone: (form)  (optional)
     - parameter eventType: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func rescanVehicleEventImageWithRequestBuilder(eventId: Int, image: URL, timezone: String? = nil, eventType: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        var localVariablePath = "/vehicle/events/{eventId}/image"
        let eventIdPreEscape = "\(APIHelper.mapValueToPathItem(eventId))"
        let eventIdPostEscape = eventIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{eventId}", with: eventIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "image": image.asParameter(codableHelper: apiConfiguration.codableHelper),
            "timezone": timezone?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "eventType": eventType?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Set or clear preferred vehicle
     
     - parameter setPreferredVehicleRequest: (body) Preferred vehicle payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func setPreferredVehicle(setPreferredVehicleRequest: SetPreferredVehicleRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await setPreferredVehicleWithRequestBuilder(setPreferredVehicleRequest: setPreferredVehicleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Set or clear preferred vehicle
     - PATCH /vehicle/preferred-vehicle
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter setPreferredVehicleRequest: (body) Preferred vehicle payload (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func setPreferredVehicleWithRequestBuilder(setPreferredVehicleRequest: SetPreferredVehicleRequest? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/preferred-vehicle"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setPreferredVehicleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Upload receipt image and create processing event draft
     
     - parameter image: (form)  
     - parameter timezone: (form)  
     - parameter eventType: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CreateDnsRecord200Response
     */
    open class func uploadVehicleReceiptImage(image: URL, timezone: String, eventType: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CreateDnsRecord200Response {
        return try await uploadVehicleReceiptImageWithRequestBuilder(image: image, timezone: timezone, eventType: eventType, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Upload receipt image and create processing event draft
     - POST /vehicle/events/receipt-image
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter image: (form)  
     - parameter timezone: (form)  
     - parameter eventType: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CreateDnsRecord200Response> 
     */
    open class func uploadVehicleReceiptImageWithRequestBuilder(image: URL, timezone: String, eventType: String? = nil, apiConfiguration: ControlPanelSDKAPIConfiguration = ControlPanelSDKAPIConfiguration.shared) -> RequestBuilder<CreateDnsRecord200Response> {
        let localVariablePath = "/vehicle/events/receipt-image"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "image": image.asParameter(codableHelper: apiConfiguration.codableHelper),
            "timezone": timezone.asParameter(codableHelper: apiConfiguration.codableHelper),
            "eventType": eventType?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateDnsRecord200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
