//
// AddAntispamMaildataRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddAntispamMaildataRequest: Sendable, Codable, Hashable {

    public var maildata: [String: JSONValue]

    public init(maildata: [String: JSONValue]) {
        self.maildata = maildata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maildata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(maildata, forKey: .maildata)
    }
}

