//
// ChangeDomainNameserversRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChangeDomainNameserversRequest: Sendable, Codable, Hashable {

    public var cname: String?
    public var dnsServersOpt: String?
    public var ns: [String]?
    public var ns1: String?
    public var ns1Ipv4: String?
    public var ns1Ipv6: String?
    public var ns2: String?
    public var ns2Ipv4: String?
    public var ns2Ipv6: String?
    public var ns3: String?
    public var ns3Ipv4: String?
    public var ns3Ipv6: String?
    public var ns4: String?
    public var ns4Ipv4: String?
    public var ns4Ipv6: String?

    public init(cname: String? = nil, dnsServersOpt: String? = nil, ns: [String]? = nil, ns1: String? = nil, ns1Ipv4: String? = nil, ns1Ipv6: String? = nil, ns2: String? = nil, ns2Ipv4: String? = nil, ns2Ipv6: String? = nil, ns3: String? = nil, ns3Ipv4: String? = nil, ns3Ipv6: String? = nil, ns4: String? = nil, ns4Ipv4: String? = nil, ns4Ipv6: String? = nil) {
        self.cname = cname
        self.dnsServersOpt = dnsServersOpt
        self.ns = ns
        self.ns1 = ns1
        self.ns1Ipv4 = ns1Ipv4
        self.ns1Ipv6 = ns1Ipv6
        self.ns2 = ns2
        self.ns2Ipv4 = ns2Ipv4
        self.ns2Ipv6 = ns2Ipv6
        self.ns3 = ns3
        self.ns3Ipv4 = ns3Ipv4
        self.ns3Ipv6 = ns3Ipv6
        self.ns4 = ns4
        self.ns4Ipv4 = ns4Ipv4
        self.ns4Ipv6 = ns4Ipv6
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cname
        case dnsServersOpt = "dns_servers_opt"
        case ns
        case ns1
        case ns1Ipv4 = "ns1_ipv4"
        case ns1Ipv6 = "ns1_ipv6"
        case ns2
        case ns2Ipv4 = "ns2_ipv4"
        case ns2Ipv6 = "ns2_ipv6"
        case ns3
        case ns3Ipv4 = "ns3_ipv4"
        case ns3Ipv6 = "ns3_ipv6"
        case ns4
        case ns4Ipv4 = "ns4_ipv4"
        case ns4Ipv6 = "ns4_ipv6"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cname, forKey: .cname)
        try container.encodeIfPresent(dnsServersOpt, forKey: .dnsServersOpt)
        try container.encodeIfPresent(ns, forKey: .ns)
        try container.encodeIfPresent(ns1, forKey: .ns1)
        try container.encodeIfPresent(ns1Ipv4, forKey: .ns1Ipv4)
        try container.encodeIfPresent(ns1Ipv6, forKey: .ns1Ipv6)
        try container.encodeIfPresent(ns2, forKey: .ns2)
        try container.encodeIfPresent(ns2Ipv4, forKey: .ns2Ipv4)
        try container.encodeIfPresent(ns2Ipv6, forKey: .ns2Ipv6)
        try container.encodeIfPresent(ns3, forKey: .ns3)
        try container.encodeIfPresent(ns3Ipv4, forKey: .ns3Ipv4)
        try container.encodeIfPresent(ns3Ipv6, forKey: .ns3Ipv6)
        try container.encodeIfPresent(ns4, forKey: .ns4)
        try container.encodeIfPresent(ns4Ipv4, forKey: .ns4Ipv4)
        try container.encodeIfPresent(ns4Ipv6, forKey: .ns4Ipv6)
    }
}

