//
// CheckCartCouponRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CheckCartCouponRequest: Sendable, Codable, Hashable {

    public var couponCode: String
    public var cname: String?

    public init(couponCode: String, cname: String? = nil) {
        self.couponCode = couponCode
        self.cname = cname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case couponCode = "coupon_code"
        case cname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(couponCode, forKey: .couponCode)
        try container.encodeIfPresent(cname, forKey: .cname)
    }
}

