//
// CreateCartItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateCartItemRequest: Sendable, Codable, Hashable {

    public var productName: String
    public var cname: String?
    public var domain: String?
    public var itemCount: Int?
    public var currencyId: String?
    public var parameters: JSONValue?
    public var processType: String?
    public var lang: String?

    public init(productName: String, cname: String? = nil, domain: String? = nil, itemCount: Int? = nil, currencyId: String? = nil, parameters: JSONValue? = nil, processType: String? = nil, lang: String? = nil) {
        self.productName = productName
        self.cname = cname
        self.domain = domain
        self.itemCount = itemCount
        self.currencyId = currencyId
        self.parameters = parameters
        self.processType = processType
        self.lang = lang
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productName = "product_name"
        case cname
        case domain
        case itemCount = "item_count"
        case currencyId = "currency_id"
        case parameters
        case processType = "process_type"
        case lang
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productName, forKey: .productName)
        try container.encodeIfPresent(cname, forKey: .cname)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(itemCount, forKey: .itemCount)
        try container.encodeIfPresent(currencyId, forKey: .currencyId)
        try container.encodeIfPresent(parameters, forKey: .parameters)
        try container.encodeIfPresent(processType, forKey: .processType)
        try container.encodeIfPresent(lang, forKey: .lang)
    }
}

