//
// CreateOauthRequest200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOauthRequest200ResponseData: Sendable, Codable, Hashable {

    public var verifyToken: String?
    public var accessToken: String?
    public var redirectUrl: String?
    public var verifyUrl: String?
    public var verifyIntervalSeconds: Int?

    public init(verifyToken: String? = nil, accessToken: String? = nil, redirectUrl: String? = nil, verifyUrl: String? = nil, verifyIntervalSeconds: Int? = nil) {
        self.verifyToken = verifyToken
        self.accessToken = accessToken
        self.redirectUrl = redirectUrl
        self.verifyUrl = verifyUrl
        self.verifyIntervalSeconds = verifyIntervalSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case verifyToken = "verify_token"
        case accessToken = "access_token"
        case redirectUrl = "redirect_url"
        case verifyUrl = "verify_url"
        case verifyIntervalSeconds = "verify_interval_seconds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(verifyToken, forKey: .verifyToken)
        try container.encodeIfPresent(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(redirectUrl, forKey: .redirectUrl)
        try container.encodeIfPresent(verifyUrl, forKey: .verifyUrl)
        try container.encodeIfPresent(verifyIntervalSeconds, forKey: .verifyIntervalSeconds)
    }
}

