//
// CreateDnsRecordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDnsRecordRequest: Sendable, Codable, Hashable {

    public var name: String
    public var type: String
    public var content: String
    public var ttl: Int
    public var prio: Int?

    public init(name: String, type: String, content: String, ttl: Int, prio: Int? = nil) {
        self.name = name
        self.type = type
        self.content = content
        self.ttl = ttl
        self.prio = prio
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case content
        case ttl
        case prio
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(content, forKey: .content)
        try container.encode(ttl, forKey: .ttl)
        try container.encodeIfPresent(prio, forKey: .prio)
    }
}

