//
// CreateMailboxRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateMailboxRequest: Sendable, Codable, Hashable {

    public var username: String
    public var password: String
    public var name: String

    public init(username: String, password: String, name: String) {
        self.username = username
        self.password = password
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
        try container.encode(name, forKey: .name)
    }
}

