//
// CreateAntispamEmailRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAntispamEmailRuleRequest: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case senderEmail = "sender_email"
        case senderDomain = "sender_domain"
        case senderIp = "sender_ip"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var pattern: String

    public init(type: ModelType, pattern: String) {
        self.type = type
        self.pattern = pattern
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case pattern
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(pattern, forKey: .pattern)
    }
}

