//
// CreateOauthRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOauthRequestRequest: Sendable, Codable, Hashable {

    public var appName: String?
    public var appUrlHomepage: String?
    public var appUrlReturn: String?
    public var scopes: [String]?

    public init(appName: String? = nil, appUrlHomepage: String? = nil, appUrlReturn: String? = nil, scopes: [String]? = nil) {
        self.appName = appName
        self.appUrlHomepage = appUrlHomepage
        self.appUrlReturn = appUrlReturn
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appName = "app_name"
        case appUrlHomepage = "app_url_homepage"
        case appUrlReturn = "app_url_return"
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appName, forKey: .appName)
        try container.encodeIfPresent(appUrlHomepage, forKey: .appUrlHomepage)
        try container.encodeIfPresent(appUrlReturn, forKey: .appUrlReturn)
        try container.encodeIfPresent(scopes, forKey: .scopes)
    }
}

