//
// CreateAuthToken200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateAuthToken200ResponseData: Sendable, Codable, Hashable {

    public var tokenType: String?
    public var token: String?
    public var expiresIn: Int?
    public var tokenExpire: String?
    public var cname: String?
    public var scopes: [String]?

    public init(tokenType: String? = nil, token: String? = nil, expiresIn: Int? = nil, tokenExpire: String? = nil, cname: String? = nil, scopes: [String]? = nil) {
        self.tokenType = tokenType
        self.token = token
        self.expiresIn = expiresIn
        self.tokenExpire = tokenExpire
        self.cname = cname
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenType = "token_type"
        case token
        case expiresIn = "expires_in"
        case tokenExpire = "token_expire"
        case cname
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(tokenExpire, forKey: .tokenExpire)
        try container.encodeIfPresent(cname, forKey: .cname)
        try container.encodeIfPresent(scopes, forKey: .scopes)
    }
}

