//
// DeleteOauthToken200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeleteOauthToken200ResponseData: Sendable, Codable, Hashable {

    public var status: String?
    public var error: String?

    public init(status: String? = nil, error: String? = nil) {
        self.status = status
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

