//
// FinalizeVehicleEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinalizeVehicleEventRequest: Sendable, Codable, Hashable {

    public var eventType: String
    public var datetimeLocal: String
    public var timezone: String
    public var location: FinalizeVehicleEventRequestLocation
    public var purpose: String?
    public var notes: String?
    public var odometer: Int?
    public var money: FinalizeVehicleEventRequestMoney?
    public var fueling: FinalizeVehicleEventRequestFueling?

    public init(eventType: String, datetimeLocal: String, timezone: String, location: FinalizeVehicleEventRequestLocation, purpose: String? = nil, notes: String? = nil, odometer: Int? = nil, money: FinalizeVehicleEventRequestMoney? = nil, fueling: FinalizeVehicleEventRequestFueling? = nil) {
        self.eventType = eventType
        self.datetimeLocal = datetimeLocal
        self.timezone = timezone
        self.location = location
        self.purpose = purpose
        self.notes = notes
        self.odometer = odometer
        self.money = money
        self.fueling = fueling
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case datetimeLocal
        case timezone
        case location
        case purpose
        case notes
        case odometer
        case money
        case fueling
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(datetimeLocal, forKey: .datetimeLocal)
        try container.encode(timezone, forKey: .timezone)
        try container.encode(location, forKey: .location)
        try container.encodeIfPresent(purpose, forKey: .purpose)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(odometer, forKey: .odometer)
        try container.encodeIfPresent(money, forKey: .money)
        try container.encodeIfPresent(fueling, forKey: .fueling)
    }
}

