//
// FinalizeVehicleEventRequestFueling.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinalizeVehicleEventRequestFueling: Sendable, Codable, Hashable {

    public var fuelingNo: Int?
    public var fuelType: String?
    public var volume: Double?
    public var unit: String?

    public init(fuelingNo: Int? = nil, fuelType: String? = nil, volume: Double? = nil, unit: String? = nil) {
        self.fuelingNo = fuelingNo
        self.fuelType = fuelType
        self.volume = volume
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fuelingNo
        case fuelType
        case volume
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fuelingNo, forKey: .fuelingNo)
        try container.encodeIfPresent(fuelType, forKey: .fuelType)
        try container.encodeIfPresent(volume, forKey: .volume)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

