//
// FinalizeVehicleEventRequestMoney.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinalizeVehicleEventRequestMoney: Sendable, Codable, Hashable {

    public var total: Double?
    public var currency: String?

    public init(total: Double? = nil, currency: String? = nil) {
        self.total = total
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

