//
// FinalizeVehicleEventRequestLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FinalizeVehicleEventRequestLocation: Sendable, Codable, Hashable {

    public var addressText: String
    public var lat: Double
    public var lon: Double
    public var placeName: String?

    public init(addressText: String, lat: Double, lon: Double, placeName: String? = nil) {
        self.addressText = addressText
        self.lat = lat
        self.lon = lon
        self.placeName = placeName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addressText
        case lat
        case lon
        case placeName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addressText, forKey: .addressText)
        try container.encode(lat, forKey: .lat)
        try container.encode(lon, forKey: .lon)
        try container.encodeIfPresent(placeName, forKey: .placeName)
    }
}

