//
// GetDnsRecords200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDnsRecords200ResponseData: Sendable, Codable, Hashable {

    public var domainId: Int?
    public var domain: String?
    public var master: String?
    public var type: String?
    public var records: [GetDnsRecords200ResponseDataRecordsInner]?

    public init(domainId: Int? = nil, domain: String? = nil, master: String? = nil, type: String? = nil, records: [GetDnsRecords200ResponseDataRecordsInner]? = nil) {
        self.domainId = domainId
        self.domain = domain
        self.master = master
        self.type = type
        self.records = records
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainId = "domain_id"
        case domain
        case master
        case type
        case records
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domainId, forKey: .domainId)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(master, forKey: .master)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(records, forKey: .records)
    }
}

