//
// ListDomains200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListDomains200ResponseData: Sendable, Codable, Hashable {

    public var count: Int?
    public var products: [JSONValue]?

    public init(count: Int? = nil, products: [JSONValue]? = nil) {
        self.count = count
        self.products = products
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(products, forKey: .products)
    }
}

