//
// MergeCartItems200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MergeCartItems200ResponseData: Sendable, Codable, Hashable {

    public var status: String?
    public var merged: Bool?
    public var fromCname: String?
    public var toCname: String?
    public var movedItems: Int?
    public var mergedItems: Int?
    public var itemsCount: Int?

    public init(status: String? = nil, merged: Bool? = nil, fromCname: String? = nil, toCname: String? = nil, movedItems: Int? = nil, mergedItems: Int? = nil, itemsCount: Int? = nil) {
        self.status = status
        self.merged = merged
        self.fromCname = fromCname
        self.toCname = toCname
        self.movedItems = movedItems
        self.mergedItems = mergedItems
        self.itemsCount = itemsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case merged
        case fromCname = "from_cname"
        case toCname = "to_cname"
        case movedItems = "moved_items"
        case mergedItems = "merged_items"
        case itemsCount = "items_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(merged, forKey: .merged)
        try container.encodeIfPresent(fromCname, forKey: .fromCname)
        try container.encodeIfPresent(toCname, forKey: .toCname)
        try container.encodeIfPresent(movedItems, forKey: .movedItems)
        try container.encodeIfPresent(mergedItems, forKey: .mergedItems)
        try container.encodeIfPresent(itemsCount, forKey: .itemsCount)
    }
}

