//
// MergeCartItems200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MergeCartItems200Response: Sendable, Codable, Hashable {

    public var status: String
    public var retval: Int
    public var msg: String
    public var data: MergeCartItems200ResponseData
    public var requestId: Int

    public init(status: String, retval: Int, msg: String, data: MergeCartItems200ResponseData, requestId: Int) {
        self.status = status
        self.retval = retval
        self.msg = msg
        self.data = data
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case retval
        case msg
        case data
        case requestId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(retval, forKey: .retval)
        try container.encode(msg, forKey: .msg)
        try container.encode(data, forKey: .data)
        try container.encode(requestId, forKey: .requestId)
    }
}

