//
// MergeCartItemsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MergeCartItemsRequest: Sendable, Codable, Hashable {

    public var fromToken: String

    public init(fromToken: String) {
        self.fromToken = fromToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fromToken = "from_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fromToken, forKey: .fromToken)
    }
}

