//
// RegisterDomainRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RegisterDomainRequest: Sendable, Codable, Hashable {

    public var cname: String
    public var period: Int?

    public init(cname: String, period: Int? = nil) {
        self.cname = cname
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cname
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cname, forKey: .cname)
        try container.encodeIfPresent(period, forKey: .period)
    }
}

