//
// Revision200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Revision200ResponseData: Sendable, Codable, Hashable {

    public var revision: Int?

    public init(revision: Int? = nil) {
        self.revision = revision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(revision, forKey: .revision)
    }
}

