//
// SetPreferredVehicleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetPreferredVehicleRequest: Sendable, Codable, Hashable {

    public var vehicleId: String?

    public init(vehicleId: String? = nil) {
        self.vehicleId = vehicleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vehicleId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(vehicleId, forKey: .vehicleId)
    }
}

