//
// SpamDetection200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpamDetection200ResponseData: Sendable, Codable, Hashable {

    public enum Classification: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
        case spam = "spam"
        case ham = "ham"
        case unknown = "unknown"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public static let confidenceRule = NumericRule<Double>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    /** Normalized classification returned by the LLM. */
    public var classification: Classification
    /** Normalized confidence from 0 to 100. */
    public var confidence: Double
    /** Short explanation in Slovak. */
    public var reason: String
    /** Most important signals used for the classification. */
    public var signals: [String]
    /** True when the LLM call or response validation failed. */
    public var error: Bool
    /** Short technical error reason. Raw LLM response is never returned here. */
    public var errorMessage: String

    public init(classification: Classification, confidence: Double, reason: String, signals: [String], error: Bool, errorMessage: String) {
        self.classification = classification
        self.confidence = confidence
        self.reason = reason
        self.signals = signals
        self.error = error
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case classification
        case confidence
        case reason
        case signals
        case error
        case errorMessage = "error_message"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(classification, forKey: .classification)
        try container.encode(confidence, forKey: .confidence)
        try container.encode(reason, forKey: .reason)
        try container.encode(signals, forKey: .signals)
        try container.encode(error, forKey: .error)
        try container.encode(errorMessage, forKey: .errorMessage)
    }
}

