//
// SpamDetectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SpamDetectionRequest: Sendable, Codable, Hashable {

    public static let messageRule = StringRule(minLength: nil, maxLength: 20000, pattern: nil)
    /** Text message submitted via a web form. The value is treated strictly as text data. */
    public var message: String

    public init(message: String) {
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
    }
}

