//
// Time200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Time200ResponseData: Sendable, Codable, Hashable {

    public var datetime: String?
    public var timestamp: Int?

    public init(datetime: String? = nil, timestamp: Int? = nil) {
        self.datetime = datetime
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case datetime
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(datetime, forKey: .datetime)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}

