//
// UpdateDnsRecordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDnsRecordRequest: Sendable, Codable, Hashable {

    public var name: String?
    public var type: String?
    public var content: String?
    public var ttl: Int?
    public var prio: Int?

    public init(name: String? = nil, type: String? = nil, content: String? = nil, ttl: Int? = nil, prio: Int? = nil) {
        self.name = name
        self.type = type
        self.content = content
        self.ttl = ttl
        self.prio = prio
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case content
        case ttl
        case prio
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encodeIfPresent(prio, forKey: .prio)
    }
}

