//
// UpdateCartItemCountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCartItemCountRequest: Sendable, Codable, Hashable {

    public var productName: String
    public var domain: String
    public var count: Int
    public var cname: String?

    public init(productName: String, domain: String, count: Int, cname: String? = nil) {
        self.productName = productName
        self.domain = domain
        self.count = count
        self.cname = cname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productName = "product_name"
        case domain
        case count
        case cname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productName, forKey: .productName)
        try container.encode(domain, forKey: .domain)
        try container.encode(count, forKey: .count)
        try container.encodeIfPresent(cname, forKey: .cname)
    }
}

