//
// UpdateCartItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCartItemRequest: Sendable, Codable, Hashable {

    public var data: UpdateCartItemRequestData
    public var cname: String?

    public init(data: UpdateCartItemRequestData, cname: String? = nil) {
        self.data = data
        self.cname = cname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case cname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(cname, forKey: .cname)
    }
}

