//
// UpdateCartItemRequestData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCartItemRequestData: Sendable, Codable, Hashable {

    public var productName: String?
    public var productDetail: String?
    public var itemCount: Int?
    public var price: Double?
    public var productPrice: Double?

    public init(productName: String? = nil, productDetail: String? = nil, itemCount: Int? = nil, price: Double? = nil, productPrice: Double? = nil) {
        self.productName = productName
        self.productDetail = productDetail
        self.itemCount = itemCount
        self.price = price
        self.productPrice = productPrice
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productName = "product_name"
        case productDetail = "product_detail"
        case itemCount = "item_count"
        case price
        case productPrice = "product_price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productName, forKey: .productName)
        try container.encodeIfPresent(productDetail, forKey: .productDetail)
        try container.encodeIfPresent(itemCount, forKey: .itemCount)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(productPrice, forKey: .productPrice)
    }
}

