//
// VerifyOauthRequest200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VerifyOauthRequest200ResponseData: Sendable, Codable, Hashable {

    public var status: String?
    public var token: String?
    public var tokenExpire: String?
    public var cname: String?
    public var error: String?

    public init(status: String? = nil, token: String? = nil, tokenExpire: String? = nil, cname: String? = nil, error: String? = nil) {
        self.status = status
        self.token = token
        self.tokenExpire = tokenExpire
        self.cname = cname
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case token
        case tokenExpire = "token_expire"
        case cname
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(tokenExpire, forKey: .tokenExpire)
        try container.encodeIfPresent(cname, forKey: .cname)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

