//
// WhoisDomain200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WhoisDomain200ResponseData: Sendable, Codable, Hashable {

    public var domain: String?
    public var isFree: Bool?
    public var isPremium: Bool?
    public var result: Int?
    public var retval: WhoisDomain200ResponseDataRetval?
    public var prices: JSONValue?

    public init(domain: String? = nil, isFree: Bool? = nil, isPremium: Bool? = nil, result: Int? = nil, retval: WhoisDomain200ResponseDataRetval? = nil, prices: JSONValue? = nil) {
        self.domain = domain
        self.isFree = isFree
        self.isPremium = isPremium
        self.result = result
        self.retval = retval
        self.prices = prices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case isFree
        case isPremium
        case result
        case retval
        case prices
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(isFree, forKey: .isFree)
        try container.encodeIfPresent(isPremium, forKey: .isPremium)
        try container.encodeIfPresent(result, forKey: .result)
        try container.encodeIfPresent(retval, forKey: .retval)
        try container.encodeIfPresent(prices, forKey: .prices)
    }
}

